<a href="https://colab.research.google.com/github/RajeshVulasala/AI-ML/blob/main/Day_8_of_AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS** For `AI-ML`
```
1. How to import pandas
2. Creating data
3. Reading Data files
```

**Import Pandas**

In [1]:
import pandas as pd

**Creating Your Own Data**  
There are `2 crore objects` in Pandas


```
1. DataFrames
2. Series
```

**1. DataFrames:**  
--> DataFrame is a `table data`.  
--> It contains an array of entries, each of which has certain values.  
--> Each entry corresponding to a a row and a column.

In [3]:
pd.DataFrame({'yes':[50,21], 'No':[131, 2]})

   yes   No
0   50  131
1   21    2

DataFrames entries are not limited to integers

In [5]:
pd.DataFrame({'bob':['I liked it.', 'It was awful.'],
              'sue':['Pretty good.', 'Bland.']})

             bob           sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

To `Change index values` from 0,1,2,... in the DataFrame.

In [6]:
pd.DataFrame({'bob':['I liked it.', 'It was awful.'],
              'sue':['Pretty good.', 'Bland.']},
              index = ['product A', 'product B'])

                     bob           sue
product A    I liked it.  Pretty good.
product B  It was awful.        Bland.

**2. SERIES:**


*   Sequence of data values
*   if DataFrame is Table, Then `SERIES is a LIST`

In [7]:
# series
# code is same as DataFrames
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64



1. Series is a single column of a DataFrame. So, you can assign row lables to the series by using `index=` parameter.
2.  A series does not have a column name. It only has only one Overal name. we can define it using `name=` parameter.

In [8]:
pd.Series([30,40,50], index=['2023 Sale', '2024 Sales', '2025 Sales'], name='Soaps')

2023 Sale     30
2024 Sales    40
2025 Sales    50
Name: Soaps, dtype: int64

**Reading data files**  
We can't always create dataframes or Series of data. So we read the data in files.  
There are different forms of formats but most or CSV files.  
`CSV = Comma Separated Values`

## **NOTE:**
**I add my data file to the google colab. so, that according to your file you can change.**
  
You can download data sets from [**click here**](https://www.kaggle.com/datasets).  
Redirect to kaggle page.

In [9]:
df = pd.read_csv("Attacks.pcap_ISCX.csv")

## **shape:**  
**It** is an attribute to check how large the DataFrame is.

In [10]:
df.shape

(170366, 79)

## **.head()**  


*   We can examine the contentss of file by using `.head()`.
*   It shows the out put of file with first five rows and headings.

In [11]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,389,113095465,48,24,9668,10012,403,0,201.416667,203.548293,...,32,203985.500,5.758373e+05,1629110,379,13800000.0,4.277541e+06,16500000,6737603,BENIGN
1,389,113473706,68,40,11364,12718,403,0,167.117647,171.919413,...,32,178326.875,5.034269e+05,1424245,325,13800000.0,4.229413e+06,16500000,6945512,BENIGN
2,0,119945515,150,0,0,0,0,0,0.000000,0.000000,...,0,6909777.333,1.170000e+07,20400000,6,24400000.0,2.430000e+07,60100000,5702188,BENIGN
3,443,60261928,9,7,2330,4221,1093,0,258.888889,409.702161,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
4,53,269,2,2,102,322,51,51,51.000000,0.000000,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN

## pd.read_csv()


*   It has over 30 optional perameters you can specify.
* Example:  you can see in this dataset that the CSV file has a index, which pandas pick up on automatically.  
To make pandas do not use that column for the index, we can specify an `index_col` parameter

In [13]:
# Ex: index_col parameter
df = pd.read_csv('Attacks.pcap_ISCX.csv', index_col=0)
df.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
Destination Port,,,,,,,,,,,,,,,,,,,,,
389,113095465,48,24,9668,10012,403,0,201.416667,203.548293,923,...,32,203985.500,5.758373e+05,1629110,379,13800000.0,4.277541e+06,16500000,6737603,BENIGN
389,113473706,68,40,11364,12718,403,0,167.117647,171.919413,1139,...,32,178326.875,5.034269e+05,1424245,325,13800000.0,4.229413e+06,16500000,6945512,BENIGN
0,119945515,150,0,0,0,0,0,0.000000,0.000000,0,...,0,6909777.333,1.170000e+07,20400000,6,24400000.0,2.430000e+07,60100000,5702188,BENIGN
443,60261928,9,7,2330,4221,1093,0,258.888889,409.702161,1460,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
53,269,2,2,102,322,51,51,51.000000,0.000000,161,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN

As you can see the column of index is removed it means the csv file has no built in index column.

IF you want to convert you created data frame into CSV you can use this,  
`variablename.to_csv("Filename.csv")`

In [16]:
# Ex: .to_csv()
df = pd.DataFrame({'cows':[12,20], 'Goats':[22,19]}, index=['Year 1', 'Year 2'])
df

        cows  Goats
Year 1    12     22
Year 2    20     19

In [17]:
#  we can convert the above data frame into csv of filename: animals.csv
df.to_csv("animals.csv")

## **CHALLENGE**

In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

1. Create a DataFrame fruits that looks like this:  
     ![](https://storage.googleapis.com/kaggle-media/learn/images/Ax3pp2A.png)

In [18]:
# sol:
fruits = pd.DataFrame({'Apples': [30], 'Bananas':[21]})
fruits

   Apples  Bananas
0      30       21

## 2.
Create a dataframe `fruits_sales` that mathes the diagram:
![](https://storage.googleapis.com/kaggle-media/learn/images/CHPn7ZF.png)

In [19]:
# Question 2
fruit_sales = pd.DataFrame({'Apples':[35,41], 'Bananas':[21,34]}, index=['2017 Sales','2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

## 3.
Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [28]:
# Question 3
a = ['4 cups','1 cup','2 large','1 can']
b = ['Flour','Milk','Eggs','Spam']
ingredients= pd.Series(a, index=b, name='Dinner')
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

## 4.
Read the following csv dataset of wine reviews into a DataFrame called `reviews`:
# choose your file
The filepath to the csv file is `Attacks.pcap_ISCX.csv`. The first few lines look like:
```
Flow Duration,	Total Fwd Packets,	Total Backward Packets,	Total Length of Fwd Packets,	Total Length of Bwd Packets,	Fwd Packet Length Max,	Fwd Packet Length Min,	Fwd Packet Length Mean,	Fwd Packet Length Std,	Bwd Packet Length Max	,...	min_seg_size_forward,	Active Mean,	Active Std,	Active Max,	Active Min,	Idle Mean,	Idle Std,	Idle Max,	Idle Min,	Label
```

In [23]:
# question 4
a = pd.read_csv('Attacks.pcap_ISCX.csv', index_col=0)
a

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
Destination Port,,,,,,,,,,,,,,,,,,,,,
389,113095465,48,24,9668,10012,403,0,201.416667,203.548293,923,...,32,203985.500,5.758373e+05,1629110,379,13800000.0,4.277541e+06,16500000,6737603,BENIGN
389,113473706,68,40,11364,12718,403,0,167.117647,171.919413,1139,...,32,178326.875,5.034269e+05,1424245,325,13800000.0,4.229413e+06,16500000,6945512,BENIGN
0,119945515,150,0,0,0,0,0,0.000000,0.000000,0,...,0,6909777.333,1.170000e+07,20400000,6,24400000.0,2.430000e+07,60100000,5702188,BENIGN
443,60261928,9,7,2330,4221,1093,0,258.888889,409.702161,1460,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
53,269,2,2,102,322,51,51,51.000000,0.000000,161,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55641,49,1,3,6,18,6,6,6.000000,0.000000,6,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
45337,217,2,1,31,6,31,0,15.500000,21.920310,6,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
22,1387547,41,46,2728,6634,456,0,66.536585,110.129945,976,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
22,207,1,1,0,0,0,0,0.000000,0.000000,0,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
60146,50,1,2,0,0,0,0,0.000000,0.000000,0,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN

## 5.
Run the below cell code to create and disply a DataFrame called `animals`:

In [24]:
animals = pd.DataFrame({'cows':[12,20], 'Goats':[22,19]}, index=['Year 1', 'Year 2'])
animals

        cows  Goats
Year 1    12     22
Year 2    20     19

In the below cell, write code to save the above DataFrame to disk as a csv file with name `Animals.Csv`

In [25]:
# Question 5
animals.to_csv("Animals.csv")

Check if the Dataframe is Saved in CSV or not

In [26]:
#  Check wheter the above DataFrame Saved in CSV or Not

In [27]:
pd.read_csv("Animals.csv")

  Unnamed: 0  cows  Goats
0     Year 1    12     22
1     Year 2    20     19