<a href="https://colab.research.google.com/github/RajeshVulasala/AI-ML/blob/main/Day_9_of_AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PANDAS:
1. Indexing
3. Selecting
4. Assigning  
# Data set used [ton-iot.csv](https://www.kaggle.com/datasets/amaniabourida/ton-iot)

import pandass and read csv

In [ ]:
import pandas as pd
df = pd.read_csv('ton-iot.csv', index_col=0)
df

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
ts,,,,,,,,,,,,,,,,,,,,,
1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,0,normal
1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,-,-,-,0,normal
1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,SHR,...,0,0,-,-,-,bad_UDP_checksum,-,F,0,normal
1554198364,192.168.1.79,33269,192.168.1.255,15600,udp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,0,normal
1554198364,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,-,-,-,0,normal
1554198364,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,-,-,-,0,normal
1556203822,192.168.1.31,60556,192.168.1.152,80,tcp,-,0.000002,0,0,S1,...,0,0,-,-,-,-,-,-,1,dos
1556203822,192.168.1.31,60582,192.168.1.152,80,tcp,-,31.639032,0,0,S1,...,0,0,-,-,-,-,-,-,1,dos
1556203822,192.168.1.31,60584,192.168.1.152,80,tcp,-,31.634963,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60586,192.168.1.152,80,tcp,-,31.626282,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60588,192.168.1.152,80,tcp,-,31.626271,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60590,192.168.1.152,80,tcp,-,31.621206,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60592,192.168.1.152,80,tcp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60594,192.168.1.152,80,tcp,-,71.344293,0,0,S3,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60596,192.168.1.152,80,tcp,-,31.522584,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos

To display max rows or how many we want can be selected through this.
`pd.set_option()`

In [ ]:
pd.set_option('display.max_rows', 5)
df

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
ts,,,,,,,,,,,,,,,,,,,,,
1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos

In python, we can access the property of an object by accessing it as an attribute.
`filesavedVariable.attritube(or) Column name`

Or we can say it is selecting Series data out of the DataFrame.

In [ ]:
# EX:
df.src_ip

ts
1554198358     3.122.49.24
1554198358    192.168.1.79
                  ...
1556203822    192.168.1.31
1556203822    192.168.1.31
Name: src_ip, Length: 19, dtype: object

if we have a dictionary, we can access its values using the indexing `[]` operator

In [ ]:
df['src_ip']

ts
1554198358     3.122.49.24
1554198358    192.168.1.79
                  ...
1556203822    192.168.1.31
1556203822    192.168.1.31
Name: src_ip, Length: 19, dtype: object

In this both types `(df.src_ip, df['src_ip'])` the indexing operator have the advantage that it can handle column names with reserved characters in them.



```
We can access the the single value out of a series in acolumn
```

In [ ]:
# EX:
df['src_ip'][0]

KeyError: 0

The KeyError: 0 happened because you were trying to access an item in the src_ip column using [0], but the DataFrame's index uses timestamps, not numbers like 0. So, it couldn't find an index label '0'. The correct way to get the first item by its position is to use .iloc[0], which you correctly did in the second line.

So, we have use `.iloc[]`

In [ ]:
df['src_ip'].iloc[0]

'3.122.49.24'

`.loc[]` is used when i want first, second or nth index or when the index does not start from 0 or 1 if it starts with another number we can not access the first row with index 0 so we `.ioc[0]` to get the the row details irrespective of index number.

The above mwthod is called indexing in python
# **INDEXING**
Pandas has it's owm accessor operators, they are `loc`, and `iloc`

# 1. iloc
iloc = Indexed based selection  
selecting data based on its numerical position in the data.

In [ ]:
# EX: iloc
df.iloc[1]

src_ip      192.168.1.79
src_port           47260
                ...
label                  0
type              normal
Name: 1554198358, Length: 44, dtype: object

To retriew rows and columns simulteniously we use `:` operator. in native python it is called as 'everything.  
When cobined with other operators used to indicate a range of values

In [ ]:
# : operator
df.iloc[:,0]

ts
1554198358     3.122.49.24
1554198358    192.168.1.79
                  ...
1556203822    192.168.1.31
1556203822    192.168.1.31
Name: src_ip, Length: 19, dtype: object

In [ ]:
# to indicate range of values
# for example, to select the src_ip column from just 1,2, and 3 row, we have to do this.
df.iloc[:3,0]

ts
1554198358      3.122.49.24
1554198358     192.168.1.79
1554198359    192.168.1.152
Name: src_ip, dtype: object

or we could do this

In [ ]:
df.iloc[0:3,0]

ts
1554198358      3.122.49.24
1554198358     192.168.1.79
1554198359    192.168.1.152
Name: src_ip, dtype: object

or we can pass a list

In [ ]:
df.iloc[[0,1,2,3],0]

ts
1554198358      3.122.49.24
1554198358     192.168.1.79
1554198359    192.168.1.152
1554198359    192.168.1.152
Name: src_ip, dtype: object

the negative numbers can be used in section. it will start counting forward from the end of the values.

In [ ]:
df.iloc[-5:]

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
ts,,,,,,,,,,,,,,,,,,,,,
1556203822,192.168.1.31,60592,192.168.1.152,80,tcp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60594,192.168.1.152,80,tcp,-,71.344293,0,0,S3,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60596,192.168.1.152,80,tcp,-,31.522584,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos

the above code gives the last five rows in order.   
So, it's helpful to have negative numbers

# **2. loc**
Label-Based Selection  
It is to get the specific row values from particular column



```
Syntax:
df.loc[index position, 'column name']

EXAMPLE:
df.loc[0,'src_ip']
```

In [ ]:
# EX:
# we will get an error because our dataframe doesnot start from 0
# df.loc[0,'src_ip']
df['src_ip'].iloc[0]

'3.122.49.24'

In [ ]:
# : operator
df.loc[:,['src_ip',	'dst_ip',	'service',	'src_bytes',	'dst_bytes']]

                  src_ip         dst_ip service  src_bytes  dst_bytes
ts
1554198358   3.122.49.24  192.168.1.152       -    1762852   41933215
1554198358  192.168.1.79  192.168.1.255       -          0          0
...                  ...            ...     ...        ...        ...
1556203822  192.168.1.31  192.168.1.152       -          0          0
1556203822  192.168.1.31  192.168.1.152       -          0          0

[19 rows x 5 columns]

# Coosing between `loc` and `iloc`
When choosing between `loc` and `iloc` there is one thing to remember.  
The 2 methods use slightly different indexing schemes.  
EX:


```
iloc[0:10] the output will be 0,1,2,...,9.

loc[0:10] the ouput will be 0,1,2,3....,10.
```

## **INDEX MANIPULATING**
The index we use is `not immutable`. We can manipulate the index.  
The `set_index()` method helps us to manipulate.

In [ ]:
# EX:
df.set_index('ts')

KeyError: "None of ['ts'] are in the columns"

The error KeyError: "None of `['ts']` are in the columns" in the cell `gjfSrGUglRKo` means that you are trying to set a column named 'ts' as the index, but 'ts' is already the index of your DataFrame df. This is because when you loaded the data using `pd.read_csv('ton-iot.csv', index_col=0)`, the first column, which is `'ts'`, was already assigned as the DataFrame's index. Therefore, 'ts' does not exist as a regular column anymore.

In [ ]:
df = pd.read_csv('ton-iot.csv')
df

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,...,0,0,-,-,-,-,-,-,1,ddos
18,1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,...,0,0,-,-,-,-,-,-,1,ddos

In [ ]:
df.set_index('ts')

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
ts,,,,,,,,,,,,,,,,,,,,,
1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos
1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,S1,...,0,0,-,-,-,-,-,-,1,ddos

Now the `ts` is set as index of the data frame.

## Conditional Selection
selecting the data by using the conditionals

Checking through the conditional operations.

In [ ]:
# EX: checking wether all source address or from 192.168.1.31
df.src_ip == '192.168.1.31'

0     False
1     False
      ...
17     True
18     True
Name: src_ip, Length: 19, dtype: bool

This result can then be used inside of `loc` to select relevant data.

In [ ]:
df.loc[df.src_ip == '192.168.1.31']

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
8,1556203822,192.168.1.31,60556,192.168.1.152,80,tcp,-,0.000002,0,0,...,0,0,-,-,-,-,-,-,1,dos
9,1556203822,192.168.1.31,60582,192.168.1.152,80,tcp,-,31.639032,0,0,...,0,0,-,-,-,-,-,-,1,dos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,...,0,0,-,-,-,-,-,-,1,ddos
18,1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,...,0,0,-,-,-,-,-,-,1,ddos

Warning: Total number of columns (45) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.loc[(df.src_ip == '192.168.1.31') & (df.src_ip == 'udp')]

Empty DataFrame
Columns: [ts, src_ip, src_port, dst_ip, dst_port, proto, service, duration, src_bytes, dst_bytes, conn_state, missed_bytes, src_pkts, src_ip_bytes, dst_pkts, dst_ip_bytes, dns_query, dns_qclass, dns_qtype, dns_rcode, dns_AA, dns_RD, dns_RA, dns_rejected, ssl_version, ssl_cipher, ssl_resumed, ssl_established, ssl_subject, ssl_issuer, http_trans_depth, http_method, http_uri, http_version, http_request_body_len, http_response_body_len, http_status_code, http_user_agent, http_orig_mime_types, http_resp_mime_types, weird_name, weird_addl, weird_notice, label, type]
Index: []

[0 rows x 45 columns]



```
df.loc[(df.src_ip == '192.168.1.31') & (df.src_ip == 'udp')]
```
The above code tells that the if source ip should be `192.168.1.31` and and that should should be `udp`. if both conditions are `true` then it gives the output

OR Operator

In [ ]:
# EX: OR, |
df.loc[(df.src_ip == '192.168.1.31') | (df.src_ip == 'udp')]

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
8,1556203822,192.168.1.31,60556,192.168.1.152,80,tcp,-,0.000002,0,0,...,0,0,-,-,-,-,-,-,1,dos
9,1556203822,192.168.1.31,60582,192.168.1.152,80,tcp,-,31.639032,0,0,...,0,0,-,-,-,-,-,-,1,dos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,...,0,0,-,-,-,-,-,-,1,ddos
18,1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,...,0,0,-,-,-,-,-,-,1,ddos

# Built-in conditional selectors in Pandas  
There are two important in those
 1. isin `isin()`
 2. isnull `isnull()`

# 1. isin  
* let's you select data whose value `is in` a list of values.

In [ ]:
df.loc[df.src_ip.isin(['192.168.1.31', '192.168.1.79'])]

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
5,1554198364,192.168.1.79,33269,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,...,0,0,-,-,-,-,-,-,1,ddos
18,1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,...,0,0,-,-,-,-,-,-,1,ddos

# 2. isnull  
* lets you highlight values `which are empty (or not empty)`(NAN)

In [ ]:
# EX: 1
df.loc[df.proto.isnull()]

Empty DataFrame
Columns: [ts, src_ip, src_port, dst_ip, dst_port, proto, service, duration, src_bytes, dst_bytes, conn_state, missed_bytes, src_pkts, src_ip_bytes, dst_pkts, dst_ip_bytes, dns_query, dns_qclass, dns_qtype, dns_rcode, dns_AA, dns_RD, dns_RA, dns_rejected, ssl_version, ssl_cipher, ssl_resumed, ssl_established, ssl_subject, ssl_issuer, http_trans_depth, http_method, http_uri, http_version, http_request_body_len, http_response_body_len, http_status_code, http_user_agent, http_orig_mime_types, http_resp_mime_types, weird_name, weird_addl, weird_notice, label, type]
Index: []

[0 rows x 45 columns]

In [ ]:
# EX: 2
df.loc[df.proto.notnull()]

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,1556203822,192.168.1.31,60598,192.168.1.152,80,tcp,-,31.490056,0,0,...,0,0,-,-,-,-,-,-,1,ddos
18,1556203822,192.168.1.31,60600,192.168.1.152,80,tcp,-,0.006237,0,0,...,0,0,-,-,-,-,-,-,1,ddos

# Assigning Data  
* Assigning data to a DataFrame is easy.  


Syntax:


```
Ex:
df['http_resp_mime_types'] = 'html'
```

Here we assigned `http_resp_mime_types` to `html` in ton-iot.csv file

In [ ]:
df['http_resp_mime_types'] = 'html'
df['http_resp_mime_types']

0     html
1     html
      ...
17    html
18    html
Name: http_resp_mime_types, Length: 19, dtype: object

Or with an iterable values:

In [ ]:
# EX:
df['index_backwards'] = range(len(df), 0, -1)
df['index_backwards']

0     19
1     18
      ..
17     2
18     1
Name: index_backwards, Length: 19, dtype: int64

# EXERCISE  
WE WORK ON [ton-iot data set](https://www.kaggle.com/datasets/amaniabourida/ton-iot)

Run the following cell to load your data and some utility functions (including code to check your answers).

In [8]:
import pandas as pd

df = pd.read_csv("ton-iot.csv", index_col=0)
pd.set_option("display.max_rows", 5)

Look at an overview of your data by running the following line.

In [9]:
df.head()

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
ts,,,,,,,,,,,,,,,,,,,,,
1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,S0,...,0,0,-,-,-,-,-,-,0,normal
1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,OTH,...,0,0,-,-,-,-,-,-,0,normal
1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,SHR,...,0,0,-,-,-,bad_UDP_checksum,-,F,0,normal

EXERCISE Questions:
1. select the `src_ip` column from reviews and assign the result to the `desc`.
2. select the first value from any column of `df`, assign it to variable `first`.
3. select the first row of dara from `df` and assign it to `first row`.
4. select first 10 values from the `src_ip` column in `df`, assign it to `first_src_ip`.
5. select the recors with index labels `1,2,3,5 and 8`, assign the result to the variable `sample variable`.